remember-me:
  key: dladmldmlzl123

upload:
  path: /Users/cho/Documents/dev/backend/f_spring/NBE5-6-3-Team04/DevQuest-service/upload/profile

spring:
  application:
    name: NBE5-6-3-Team04

  web:
    resources:
      static-locations: classpath:/static/, file:uploads/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/todoRpg
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중엔 update 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true

gemini:
  base-url: https://generativelanguage.googleapis.com
  api-key: "AIzaSyDfNtJhfDdZAuqDr83VuUucHSKTJRfhP2A"